config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#botafogo'

  # VERB "/the_path", to: "the-controller#the-action"
  get '/botafogo', to: 'pages#botafogo', as: 'botafogo'

  get '/contact_us', to: 'pages#contact_us', as: 'contact_us'

  # VERB
  # GET/POST/PATCH/PUT/DELETE



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def botafogo
  end

  def contact_us
    @members = ["Pedro", "Gergo", "Augusto", "Alexandre"]

    @name = params[:name]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li> <%= link_to "Botafogo", botafogo_path %>  </li>
      <li> <%= link_to "Contact Us", contact_us_path %> </li>
    </ul>

    <%= yield %>

    <p>This is my footer</p>
  </body>
</html>

app/views/pages/botafogo.html.erb
<h1>Botafogo</h1>

<h2>Thanks to us, Brazil won 3 titles in the World CUp</h2>

app/views/pages/contact_us.html.erb
<h2>Don't contact us!</h2>

<form action="/contact_us" method="GET">
  <input type="text" name="name">
  <input type="text" name="address">
  <input type="submit" value="Search">
</form>

<ul>
  <% @members.each do |member| %>
    <li><%= member %></li>
  <% end %>
</ul>